sudo: required

# Install Docker
services:
  - docker

# Execute logic
script:
  - echo "Hello Students!"

after_success:
  # Build all the docker files
  - docker build -t abhay19w33/zomato-server-client ./client
  - docker build -t abhay19w33/zomato-server-server ./server
  - docker build -t abhay19w33/zomato-server-nginx ./nginx

  # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push abhay19w33/zomato-server-client
  - docker push abhay19w33/zomato-server-server
  - docker push abhay19w33/zomato-server-nginx
